### PR TITLE
#393 added model field and adjusted unit tests.

### PR DESCRIPTION
**Pull request by tdowds**
Removed the old committee preferences fields and added a ManyToManyField for committeepreferences. Adjusted unit tests accordingly. Still to do: update school serializer, update unit tests, (update Admin too?)

### CODE REVIEW

**Comment by tdowds** [comment]
Updated the serializer and updated the unit tests

**Comment by kmeht** [comment]
Looks good, but you'd still have to include the migration otherwise Travis will fail.

**Comment by tdowds** [comment]
Here's the migration

**Comment by kmeht** [comment]
@tdowds: Merged this PR, but Python convention is to separate words in a variable with an underscore. Should've been `committee_preferences`.

**Pull request closed without merging**
