### PR TITLE
Deprecate school model

### PR DESCRIPTION
**Pull request by tdowds**
This PR is for deprecating parts of the school model to transition over to using the registration model ( #331 ). Some things that will need to be done to have a fully working app:

1. Generate migration to delete fields from School model (and pass model tests)
2. Update admin code in school to reflect changed model (and pass admin model tests)
3. Transition some school admin functionality to Registration admin (and write tests)
4. Update admin functionality for Assignment to deal with having a registration field instead of a school field
5. update our API (and pass api tests)
6. Update our react components that interact with the school api 
7. Update our react components to interact with registration api (possible tests here if we need a registration store or something like that).

Not entirely sure how much of all this we want to put into this PR, but open for whatever!

### CODE REVIEW

**Comment by tdowds** [comment]
This first diff is for point 1 in the PR description.

**Comment by tdowds** [comment]
Number 2

**Comment by tdowds** [comment]
Number 4 - currently passing all tests in `huxley/core/tests`

**Comment by kmeht** [comment]
Great work so far! I'd leave 6 and 7 for another PR.

**Comment by tdowds** [comment]
Number 5 - all tests are passing

**Comment by m-j-mcdonald** [comment]
This is great! I second leaving 6 & 7 for the next PR

**Pull request merged**
