### PR TITLE
Update Django Rest Framework

### PR DESCRIPTION
**Pull request by nathanielparke**
Updates the codebase to Django Rest Framework version 3.3.1

### CODE REVIEW

**Comment by nathanielparke** [comment]
Currently failing one test:

```
FAIL: test_country_preferences (huxley.api.tests.school.test_create_school.CreateSchoolTestCase)
It should save a school's country preferences.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Nathaniel/BMUN-huxley/huxley/api/tests/school/test_create_school.py", line 134, in test_country_preferences
    self.assertEqual(response.data['countrypreferences'], [c1, c2])
AssertionError: Lists differ: [] != [1, 2]

Second list contains 2 additional elements.
First extra element 0:
1

- []
+ [1, 2]

----------------------------------------------------------------------
```

I think it relates to the school serializer having the writable field of country assignments but the serializer prevents it from writing because of the updated generic ModelSerializer specs.

**Comment by nathanielparke** [comment]
Fixed the above through the kwarg 'source' for the ListField countrypreference to autopopulate the countrypreferences field.

**Comment by nathanielparke** [comment]
In testing this code on my local host I hit an error with the serializer that was related to writing to a nested serializer. Line that is throwing this in the user serializer that is calling the ModelSerializer's create method. 

```
user = super(CreateUserSerializer, self).create(validated_data)
```

This case is currently not being caught by the UserListPostTestCase so we need to investigate that before merging this code. Included is the stack trace for the error.

```
Traceback (most recent call last):
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
  File "/Users/Nathaniel/BMUN-huxley/huxley/api/views/user.py", line 28, in create
    return super(UserList, self).create(request, *args, **kwargs)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/Users/Nathaniel/BMUN-huxley/huxley/api/serializers/user.py", line 41, in create
    user = super(CreateUserSerializer, self).create(validated_data)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/serializers.py", line 832, in create
    raise_errors_on_nested_writes('create', self, validated_data)
  File "/Users/Nathaniel/.virtualenvs/huxley/lib/python2.7/site-packages/rest_framework/serializers.py", line 724, in raise_errors_on_nested_writes
    class_name=serializer.__class__.__name__
AssertionError: The `.create()` method does not support writable nestedfields by default.
Write an explicit `.create()` method for serializer `huxley.api.serializers.user.CreateUserSerializer`, or set `read_only=True` on nested serializer fields.
```

**Comment by nathanielparke** [comment]
Currently the only thing wrong with this PR is the field requirements for submit. DRF 3.3 by default sets all the fields of a model to be required unless otherwise stated. This however can cause errors that are difficult to track from a user's point of view. Essentially if a user doesn't provides a value for a field that the serializer deems as required the server sends back a 400 message and the user is never notified. 

I am of the mindset that we should change the JS code to render all errors relating to required fields and set all the serializer fields required to be False, this way the school will register whether or not data is missing as long as React allows it. 

Open to suggestions or recommendations. 

@tdowds @kmeht

**Comment by kmeht** [comment]
Closing in favor of #442.

**Pull request closed without merging**
