### PR TITLE
Front End Update for Registration Model

### PR DESCRIPTION
**Pull request by tdowds**
This PR is to update our front end code to work with our Registration model ( #331 ). Some things to do in this PR:

1. Get the Registration object and populate the correct fields
2. Update the Registration object when finalizing assignments
3. Write and update tests

### CODE REVIEW

**Comment by tdowds** [comment]
1

**Comment by tdowds** [comment]
2

**Comment by tdowds** [comment]
3

**Comment by m-j-mcdonald** [comment]
This looks good to me! The only thing I think might worth revisiting is the structure of the registrationstore; it theoretically could end up in a situation where it allows a user access to a registration they don't have permission to view (if a previous user accesses a registration and then somehow the new user queries that schoolID & conferenceID). The scenario's far fetched and I don't think it's an issue, but we could consider something like what we do in delegate store.

**Pull request merged**
