### PR TITLE
Major Frontend Upgrades + Huxley Notes + Sheets Integration + Zoom-links

### PR DESCRIPTION
**Pull request by mathildepm**
Wow! Major updates to huxley.

### CODE REVIEW

**Review by shaynak — APPROVED** [review]
big changes! lgtm :)

**Comment by kmeht** [comment]
@mathildepm Didn't there used to be an option to squash and merge? Allows each PR to be merged as one commit, cleaning up all those intermediary commits that don't need to be in history.

**Comment by kmeht** [comment]
Also wow, this is a massive update!

**Comment by mathildepm** [comment]
@kmeht Thanks! looks like we got ahead of ourselves with the merge. Should be cleaned up now!

**Comment by kmeht** [comment]
Some cool features in here, like delegates sending notes to each other and the chair. Did the pandemic spur this new feature development?

**Comment by shaynak** [comment]
Yup, we wanted to create a system that allowed delegates to communicate with us being able to see to ensure that delegates don't get harassed over Zoom chat!

**Pull request merged**
